-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS uuid-ossp;

-- Create non-root users with limited privileges
DO $$ 
BEGIN
    -- n8n user
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${POSTGRES_NON_ROOT_USER}') THEN
        CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
    END IF;

    -- Keycloak user
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${KC_DB_USERNAME}') THEN
        CREATE USER ${KC_DB_USERNAME} WITH PASSWORD '${KC_DB_PASSWORD}';
    END IF;

    -- Baserow user
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = 'baserow') THEN
        CREATE USER baserow WITH PASSWORD '${BASEROW_DB_PASSWORD}';
    END IF;
END
$$;

-- Create databases
CREATE DATABASE keycloak;
CREATE DATABASE baserow;
CREATE DATABASE n8n;

-- Configure keycloak database
\c keycloak
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO ${KC_DB_USERNAME};
GRANT ALL PRIVILEGES ON SCHEMA keycloak TO ${KC_DB_USERNAME};
ALTER DATABASE keycloak OWNER TO ${KC_DB_USERNAME};

-- Configure baserow database
\c baserow
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS uuid-ossp;
GRANT ALL PRIVILEGES ON DATABASE baserow TO baserow;
ALTER DATABASE baserow OWNER TO baserow;

-- Configure n8n database
\c n8n
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
GRANT ALL PRIVILEGES ON DATABASE n8n TO ${POSTGRES_NON_ROOT_USER};
ALTER DATABASE n8n OWNER TO ${POSTGRES_NON_ROOT_USER};

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_NON_ROOT_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA keycloak 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${KC_DB_USERNAME};

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO baserow;
